# Generated by Django 4.2.7 on 2025-11-21 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KMLJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("rotas", "Com Rotas (Google Maps)"),
                            ("simples", "Simples (Apenas Pontos)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("input_file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="outputs/%Y/%m/%d/"
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("processed_items", models.IntegerField(default=0)),
                ("skipped_items", models.IntegerField(default=0)),
                (
                    "routes_created",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "KML Job",
                "verbose_name_plural": "KML Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
