# Generated by Django 4.2.7 on 2025-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kmljob",
            name="log_file",
            field=models.FileField(blank=True, null=True, upload_to="logs/%Y/%m/%d/"),
        ),
    ]
